title: Spongestrips Generator
lead: Bedazzle the world with your demented mind. Use this handy web tool to create your very own spongestrips!

# Build settings
markdown: kramdown

sass:
  style: compressed
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _scripts